### ISSUE TITLE
open suttas with id as anchor 

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#14]
Good day! Hope you are doing great.

i've made some little but helpful update and now all qoutes in results have line id as an anchor to the sutta 
[example of search results](https://find.dhamma.gift/result/adhivacanasamphasso_suttanta_pali_1-2.html)

also i've updated the sc-light code, so these anchors are really there on the page
[example of the sc-light sutta with anchors](https://find.dhamma.gift/sc/?q=dn15&lang=pli#dn15:20.2)

But i can't get smooth or whatever scrolling working in sc-light. i've googled for a few solutions for dinamycally generate javascript pages but they don't work.

Could you please help me a bit? or may be it'll be even a nice feature for original sc-light so links could be shared with exact qoute and without need to search for the quote manually.

**Comment by thesunshade** [comment]
Hmm. When I go to https://find.dhamma.gift/sc/?q=dn15&lang=pli#dn15:20.2 I don't see any ids:
![image](https://github.com/thesunshade/mini-sc/assets/82448383/1801d668-ead3-4d5d-a9b1-fc4748239a9f)

Are you sure you have pushed your changes?

And so I understand the issue, you want to be able to include an id in the url and have the browser take you directly there? I don't know if that is possible since this is a single page app and the page is built using the parameters (e.g. `q=dn15&lang=pli`). But first, let's make sure that the ids are on the page.

**Comment by thesunshade** [comment]
Did you ever get this figured out @o28o ?
