### ISSUE TITLE
Licence for this project?

### ISSUE THREAD

**Issue by ishaanv** [thesunshade/mini-sc#15]
Find the lightweight interface great! I was wondering if it's possible to modify and deploy with attribution of course @thesunshade?

Thanks

**Comment by thesunshade** [comment]
The code itself is so simplistic that it would be hard to claim any license on it, lol.

Someone else is already using it to do some different things here: https://find.dhamma.gift/sc/?q=mn123

I guess I'd just ask that you change it as much as possible (maybe a bit more than the link above) so it's clear it's a different project. No need to give attribution. But be sure to change the github repo link as well as the og tags in the index.html header.

In a way it's just a proof of concept—How much can you strip things down and still get the suttas. It has some obvious shortcomings. For example, it depends on having the exactly correct UID, so that means that `dhp123` will fail. You have to give it `dhp116-128`. I think that the dhamma.gift site has bulked it up so that there is a list presented of valid ids as you type. So you may actually want to fork that version.

Good luck!

**Comment by ishaanv** [comment]
Yep that makes sense. I was just considering using this as a starting point for going from the bilara data json files to a clean, quick website.

Like you said search can be improved in addition to also displaying comment json files. 

For sure will try to make is obvious that this will be a different project.

Thanks again publishing this and making it available to use.

**Comment by thesunshade** [comment]
You're most welcome. You might want to checkout https://discourse.suttacentral.net/tag/api-documentation

There's certianly lots of fun things you can do. This particular app was just to see if I could get it under 5kb. I think if you left off the icons and fonts it might still be at that.

You can also pull data right from Github. This is a variation that does that I think: https://bp.readingfaithfully.org/

**Comment by ishaanv** [comment]
That's great, thanks again. I'm helping someone share their translations and your initial project and the site you just linked are helpful with this.
