### ISSUE TITLE
Toggle pali

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#6]
Hi there. Thank you for project. I use it in mine find.dhamma.gift as output links for searched words . I like that it works faster then suttacentral.

But the pages opened on https://sc.readingfaithfully.org have only 2 options
With pali and without. 

Could you please make 3 options. 
1 line by line with pali
2 only pali 
3 only english 

That could be great 

If you'll be able to add it I'll change all eng and pali links to your project and won't use suttacentral.net links at all.

Anyways. Thank you for the project again😄🙏

**Comment by thesunshade** [comment]
I'm so glad you find it helpful! And I appreciate the time you took to let me know.

This site was originally just meant as a proof of concept to see how small an interface could be. Still, I'm trying to use the 80/20 rule when considering adding new features. I don't think many people would need a Pali only version. 

But! Since you have your own domain (do you?) if you can set up a dns record for a new subdomain, then you can host your own version of this site. For the sc.readingfaithfully.org I'm just using the free hosing with Netlify. It can be as simple as dragging and dropping the three files that make the site (index.html, index.css, index.js) into Netlify and you are good to go.

If you want to fork this project, I'd be happy to add the Pali option. I could even "unbrand" it. That would also allow you to make the styling match your project.

**Comment by thesunshade** [comment]
OK, let me think...

Yes, you first would fork. 

Then in Netlify, you would go to your "overview" page and find "Add new site"
![image](https://user-images.githubusercontent.com/82448383/191642099-0925e344-446f-42ec-98c4-5e86d6df7475.png)

Then import an existing project. 

You will have to then link your Netlify and Github accounts. Should just be a click or two.

Then pick the repo you want to publish. Default settings should be correct.

Netlify will publish the site with a madeup url that ends in Netlify.app. I suggest renaming it to something that makes sense. It will still have to end in netlify.app.

Then go to "site overview" for that site:
![image](https://user-images.githubusercontent.com/82448383/191642582-778905a8-725f-4771-843b-bb5b1e49a2ba.png)

And click "domain settings"

The review these articles to explain setting up the DNS record:
https://docs.netlify.com/domains-https/custom-domains/
https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/

When all that is done, give me the link to the repo and I'll add the Pali only. What I'll do is make a branch of the repo, make the changes, then submit a pull request to you. If all goes as expected, then accepting the pull request should make the changes life on your version of the site.

**Comment by o28o** [comment]
Thank you so much.
I already made http://sc.dhamma.gift/?q=Mn148 it's available)))
Ssl cert will add a bit later. 

--
Sent from Mail.ru app for Android Wednesday, 21 September 2022, 10:10PM -04:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
And the forked project is https://github.com/o28o/mini-sc-pali
I would love to add this function by myself and not trouble you. But I don't know how😁😄
--
Sent from Mail.ru app for Android Wednesday, 21 September 2022, 10:10PM -04:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
Oh wow! Thrilling!

So, how would you like to deal with the Pali. I could just add the Pali only into the cycle of the existing button, so it would toggle through `PaliEnglish`, `English`, `Pali`.

**Comment by o28o** [comment]
Yes. Thank you so much for help
I think it'll be the best option. Just to toggle them. Especially if it's not time consuming for you.
Just asking: 😁 Is it possible  to open particular language with get request? E.g. ?q=148&lang=pali eng or both
--
Sent from Mail.ru app for Android Wednesday, 21 September 2022, 10:20PM -04:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
> Is it possible

Well, with code, (almost!) anything is possible. I actually expected you to ask about that 😁.

I've never done that exact thing (i.e. having two different props) but it shouldn't be hard. Give me a couple of days.

You can see at line 212 in the .js file that it first checks to see if the language has been saved in `localStorage`. I guess we'd just bypass that setting if the url contained a language value. The logic will need to be changed a bit. It's just changing the css class of the Pali to show or hide. 

What do you think about 
`lang=eng`
`lang=pli`
`lang=pli-eng`

Also, just an fyi, this app is only using the Bilara data on Sutta Central. As far as I know there are no Russian translations in the Bilara system so I won't be able to add that as an option.

**Comment by thesunshade** [comment]
@o28o,

Couple of questions.

1) Do you expect clicking on the `Toggle Pali` button to add the parameters to the url in the browser? Or were you only hoping to be able to put them in a url and then have the appropriate language load?

2) Do you expect the last *use selected* language to be stored in the browser so that the next time a url without a parameter loads, it will remember the user's preference?

**Comment by o28o** [comment]
So both of us are new to that:-) 
 
Very nice job and very fast! I checked everything works as expected. Very nice! both and lang from url and the toggle. Thank you for that 
 
So regarding the forked repo what i did was:
*  deleted the old one.
*  copied your initial project  https://github.com/thesunshade/mini-sc  as a zip file to the server and
*  pushed in into new repo  https://github.com/o28o/mini-sc-pali  (name is old, but it’s not fork anymore)
 
Is that what you mean by breaking all ties? Hope it did the job. coz now it’s completley separate copy
 
Best Regards
Pavel K.

+7 777 935 28 28
https://petlichka.kz

**Comment by thesunshade** [comment]
Yes, that's one way to do it. There is also a somewhat hidden option to import under the `+` button drop down at the top of all pages. Next to your profile image.

Well, most of my time was taken up 
* figuring out how my own code worked
* fixing the crazy way I did things
* figuring out how github worked

I also stripped out a hidden feature that was really just for my own benefit. Should make the code easier to read.

If the original app was not trying to be mini, I would have put some of the js into separate modules. But as it is the bulk of the code in the JS file is the "home" page. Even as I type I'm thinking of ways that could have (should have!) just been put in the HTML page.

And don't miss the fact that the only citations that work in this app are the exact locators used for the  real pages on SuttaCentral. This means that while `Dhp1` will give you the first verse on suttascentral.net, it won't work here because the real link is `https://suttacentral.net/dhp1-20/en/sujato`. This is true for all the "range" pages.

I have made a pull request with my changes. You should just be able to accept them, assuming you haven't made any changes since I cloned the repo.

**Comment by o28o** [comment]
Hi there. 
I've merged the changes by pressing "merge" button in the app. But there are still 2 toggle options and no lang from url.
https://sc.dhamma.gift/?q=Mn115&lang=pli
Did I do something wrong?
About the html og and other meta thank you. I'll change it. 
Links to your other resources I think should stay. There are English speaking guys who use find, so they might benefit from readingfaithfully.org
--
Sent from Mail.ru app for Android Thursday, 22 September 2022, 10:53PM -04:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
> Did I do something wrong?

Hmm. It looks like the code is there in your repo. And there are no pending PRs. (I often find that there is more clicking involved in accepting a PR than I expect, but you have for sure done it correctly.) I'm guessing that there is something wrong with the Netlify build? Because for sure the new code is not being used in the link you gave.

One thing to check on Netlify is the build/deploy history. Maybe somewhere in the process of redoing things, the connection to Netlify got borked.

**Comment by thesunshade** [comment]
Looks like you got it to work. Sadhu!! Was it the Netlify stuff?

**Comment by o28o** [comment]
Hi
Seems like it was the cache issue. Hosting was OK.
Sadhu
--
Sent from Mail.ru app for Android Friday, 23 September 2022, 09:36PM -04:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
That worked)))

I think it was because of client browser cache. Now i see pali there. https://sc.dhamma.gift/?q=Mn115&lang=pli
And urls are working😄😄😄
So cool!!! Thank you so much. 
--
Sent from Mail.ru app for Android Friday, 23 September 2022, 04:43AM -04:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
Sounds great.
Yeah they dont have russian line by line unfortunately. So for  just russian I use different site
Sorry for off top. Are you in USA or somewhere else? I'm currently having solo forest retreat in Nashville Indiana. preparing to become a monk. But leaving US soon.
--
Sent from Mail.ru app for Android Wednesday, 21 September 2022, 10:40PM -04:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
Will it be possible to make this order: pali, pali english, english.
So if someone will like the English first they will read from your domain. And dhamma gift will be pali 1st))))
--
Sent from Mail.ru app for Android Wednesday, 21 September 2022, 10:24PM -04:00 from Pavel Katorgin  ***@***.*** :

**Comment by thesunshade** [comment]
> Are you in USA or somewhere else? I'm currently having solo forest retreat in Nashville Indiana. preparing to become a monk. But leaving US soon.

Why don't you drop me a line at info@readingfaithfully.org.

For the toggle order, you can see this code:
https://github.com/o28o/mini-sc-pali/blob/52ce4ca255627630299affe9c527ece42a5517cd/index.js#L215-L245

As far as the initial state, I think it is set here:
https://github.com/o28o/mini-sc-pali/blob/52ce4ca255627630299affe9c527ece42a5517cd/index.js#L10
